services:
    yamilovs.sypex_geo.manager:
        class: YamilovS\SypexGeoBundle\Manager\SypexGeoManager
        arguments:
            - "@file_locator"
            - "%yamilovs_sypex_geo.mode%"
            - "%yamilovs_sypex_geo.database_path%"

    YamilovS\SypexGeoBundle\Command\UpdateDatabaseFileCommand:
        tags: ['console.command']
        arguments:
            - "%yamilovs_sypex_geo.connection%"
            - "%yamilovs_sypex_geo.database_path%"
            - "@filesystem%"

    YamilovS\SypexGeoBundle\Command\GetIpDataCommand:
      tags: ['console.command']
      arguments:
        - "@yamilovs.sypex_geo.manager"